### ISSUE TITLE
Failing to Login

### ISSUE THREAD

**Issue by bs-wc** [niko247/tind3r-ext#3]
Hi there, 

Is this extension still active and being updated? 

The past two days the extension hasn't been able to log into Facebook. It just freezes on 'refresh token FB' 

Is there anything I can do to stop this? 

Thanks

**Comment by bs-wc** [comment]
I guess this isn't active anymore...

**Comment by niko247** [comment]
> Hi there,
> 
> Is this extension still active and being updated?
> 
> The past two days the extension hasn't been able to log into Facebook. It just freezes on 'refresh token FB'
> 
> Is there anything I can do to stop this?
> 
> Thanks

It works fine, maybe you don't have latest version. Download it from here:
https://github.com/niko247/tind3r-ext/issues/1  the link is inside on top of the thread

**Comment by bs-wc** [comment]
> > Hi there,
> > Is this extension still active and being updated?
> > The past two days the extension hasn't been able to log into Facebook. It just freezes on 'refresh token FB'
> > Is there anything I can do to stop this?
> > Thanks
> 
> It works fine, maybe you don't have latest version. Download it from here:
> #1 the link is inside on top of the thread

Thank you for the response. I have downloaded that update, but each time I try to open the command (on Mac) it says:

Downloads/TIND3R/osx_tind3r_run_me.command: line 3: ./libs/openjdk-12.0.1_osx-x64_bin/jdk-12.0.1.jdk/Contents/Home/bin/java: Permission denied

**Comment by bs-wc** [comment]
Thank you! That fixed it.
